routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');

Route::get('/about', 'HomeController@about')->name('about');

/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');

    Route::get('logout', 'LoginController@logout')->name('logout');

//    Route::post('register', 'RegisterController@register')->name('post.technicians');

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Admin routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>'admin'], function () {

    Route::group(['namespace'=>'Admin'], function(){

        // Dashboard
        Route::get('/', 'DashboardController@dashboard')->name('dashboard');

        // Charts
        Route::get('charts/', 'DashboardController@charts')->name('charts');

        // New Subscription plan
        Route::post('subscriptions/create/', 'DashboardController@createSubscription')->name('subscription.new');

        // Subscription plans
        Route::get('subscriptions/', 'DashboardController@subscriptions')->name('subscriptions');
        
        // Users
        Route::get('users', 'AdminController@index')->name('users');

    });

    /**
    * @Technicians
    */

    // All Technicians
    Route::get('technicians', 'TechnicianController@technicians')->name('technicians');

    // Technicians Map
    Route::get('technicians/map', 'TechnicianController@map')->name('technicians.map');

    // Get technician Certificates
    Route::get('technician/certificate/{filename}', 'TechnicianController@certificate')->name('technicians.certificate');

    // Get technician Good Conduct
    Route::get('technician/{user_id}/good-conduct/', 'TechnicianController@goodConduct')->name('technicians.good-conduct');

    // Get technician Good Conduct
    Route::get('technician/{user_id}/id-card/', 'TechnicianController@nationalIdCard')->name('technicians.id-card');

    // Technician Details
    Route::get('technician/{user}', 'TechnicianController@show')->name('technician.show');

    // Edit Technician Details
    Route::get('technician/{user}/edit', 'TechnicianController@edit')->name('technician.edit');

    // Delete User
    Route::delete('technician/{user}', 'TechnicianController@destroy')->name('users.destroy');

    // Get Technicians Coordinates
    Route::get('technicians/coordinates', 'TechnicianController@getCoordinates')->name('technicians.coords');

    // Activate Account
    Route::get('technician/activate/{id}', 'TechnicianController@activate')->name('technician.activate');

    // Deactivate Account
    Route::get('technician/deactivate/{id}', 'TechnicianController@deactivate')->name('technician.deactivate');

    /**
    * @Clients
    */

    // All Clients
    Route::get('clients/', 'ClientController@clients')->name('clients');

    // Activate Account
    Route::get('clients/activate/{id}', 'ClientController@activate')->name('clients.activate');

    // Deactivate Account
    Route::get('clients/deactivate/{id}', 'ClientController@deactivate')->name('clients.deactivate');

    /**
    * @Jobs
    */

    // All Jobs
    Route::get('/jobs', 'JobController@getAll')->name('jobs');
    
    // Complete Jobs
    Route::get('/jobs/complete', 'JobController@getAll')->name('jobs.complete');

    // Canceled Jobs
    Route::get('/jobs/canceled', 'JobController@cancelled')->name('jobs.canceled');

    // Unasigned Jobs
    Route::get('/jobs/unasigned', 'JobController@unasigned')->name('jobs.unasigned');

    // Assigned Jobs
    Route::get('/jobs/assigned', 'JobController@assigned')->name('jobs.assigned');


    /**
    * @Companies
    */

    // All Companies
    Route::get('companies', 'CompanyController@getAll')->name('companies');

    // New Company
    Route::get('companies/new', 'CompanyController@create')->name('companies.new');
    
    // Edit Company
    Route::post('companies/edit', 'CompanyController@edit')->name('companies.edit');

    // Preview Company
    Route::get('companies/show', 'CompanyController@preview')->name('companies.show');

    // Company map
    Route::get('companies/map', 'CompanyController@map')->name('companies.map');

    // Get Company Coordinates
    Route::get('companies/coordinates', 'CompanyController@getCoordinates')->name('companies.coords');


    /**
    * @Categories
    */

    // Get all catergories
    Route::get('categories', 'CategoryController@index')->name('categories');

    // Create new category
    Route::post('categories/new', 'CategoryController@create')->name('categories.create');

    // Delete category
    Route::post('category/delete', 'CategoryController@delete')->name('category.delete');

    // Get category view
    Route::get('categories/{slug}','CategoryController@services')->name('category.view');

    /**
    * @Services
    */

    // Create new category
    Route::post('service/new', 'ServiceController@create')->name('service.create');

    // Get service
    Route::get('service/get', 'ServiceController@get')->name('service.get');

    // Edit Service
    Route::post('service/edit', 'ServiceController@edit')->name('service.edit');

    // Delete Service
    Route::post('service/delete', 'ServiceController@delete')->name('service.delete');


    // Route::get('permissions', 'PermissionController@index')->name('permissions');
    // Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');


    // Reports
    Route::get('/reports', 'ReportsController@index')->name('reports');

    Route::get('/reports/filter/technicians', 'ReportsController@technicians')->name('filterby.tech');

    Route::get('reports/jobs/print/', 'ReportsController@printJobReports')->name('jobs.print');

    Route::get('reports/technicians/print/', 'ReportsController@printTechReports')->name('technicians.print');
});

// Technician Avatar
Route::get('technician/avatar/{filename}', [
  'uses'=> 'TechnicianController@avatar',
  'as'=>'avatar',
]);

// Fundi Profile / dashboard
Route::group(['prefix'=>'fundi'], function (){

    //
    Route::match(['get', 'post'], 'signup/', 'TechnicianController@register')->name('become.fundi');

    //
    Route::get('signup/process/{uid}', 'TechnicianController@selectState')->name('fundi.state');

    //
    Route::get('signup/process/{uid}/finish/', 'TechnicianController@create');

    //
    Route::get('signup/successful/{uid}', 'TechnicianController@signupSuccess')->name('fundi.success');

    //
    Route::get('send-app-link/{uuid}', 'TechnicianController@sendLink');

    //
    Route::group(['middleware'=>'auth:web'], function (){

        //
        Route::get('dashboard/', 'TechnicianController@fundiDashboard')->name('fundi.dashboard');

        //
        Route::get('dashboard/documents/', 'TechnicianController@fundiDocuments')->name('fundi.documents');

        //
        Route::get('dashboard/settings/', 'TechnicianController@settings')->name('fundi.settings');

        //
        Route::post('update/', 'TechnicianController@update')->name('fundi.update');

        //
        Route::post('upload/certificate', 'TechnicianController@uploadCertificate');

        //
        Route::post('upload/certificate-of-good-conduct', 'TechnicianController@uploadCertificateOfGoodConduct');

        //
        Route::post('upload/national-id-card', 'TechnicianController@uploadNationaIdCard');

        //
        Route::post('upload/profile-pic', 'TechnicianController@uploadProfilePic');

    });

});

// View category services
Route::get('category/service/{slug}','ServiceController@fetchServices')->name('category.services');


Route::get('/fundi/test/{uid}', 'TechnicianController@selectService');

app/Technician.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Models\Auth\User\User;
use App\Company;
use Carbon\Carbon;
use App\Models\Traits\Model as ModelTrait;

class Technician extends Model
{
    use ModelTrait;
    
    protected $hidden = [];

    protected $guarded = [];

    protected $table = 'technicians';

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class, 'company_employees', 'user_id', 'company_id');
    }

    public function isValidated()
    {
        if ($this->id_card_no == null || !$this->certificate_valid || !$this->$good_conduct_valid) {
            return false;
        }
        return true;
    }

    /**
     * Format createdate (m-d-Y: h:i:s)
     *
     * @param string
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        $date = new Carbon($value);
        return $date->format('m-d-Y: h:i:s');
    }

    /**
     * Format updatedate (m-d-Y: h:i:s)
     *
     * @param string
     * @return string
     */
    public function getUpdatedAtAttribute($value)
    {
        $date = new Carbon($value);

        return $date->format('m-d-Y: h:i:s');
    }
}

resources/views/admin/technician/all.blade.php
@extends('admin.layouts.admin')

@section('title', 'Technicians')

@section('content')
    <div class="row">
      <div class="col-md-3 col-sm-3 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input id="searchInput" type="text" onkeyup="searchTable()" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>@sortablelink('email', __('views.admin.users.index.table_header_0'),['page' => $users->currentPage()])</th>
                <th>@sortablelink('name',  __('views.admin.users.index.table_header_1'),['page' => $users->currentPage()])</th>
                <th>{{ __('views.admin.users.index.table_header_2') }}</th>
                <th>@sortablelink('active', __('views.admin.users.index.table_header_3'),['page' => $users->currentPage()])</th>
                <th>@sortablelink('confirmed', __('views.admin.users.index.table_header_4'),['page' => $users->currentPage()])</th>
                <th>@sortablelink('created_at', __('views.admin.users.index.table_header_5'),['page' => $users->currentPage()])</th>
                <th>@sortablelink('updated_at', __('views.admin.users.index.table_header_6'),['page' => $users->currentPage()])</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody id="table">
            @foreach($users as $user)
              @if ($user->hasRole('technician') && !$user->hasRole('administrator'))
                <tr>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->first_name }}</td>
                    <td>{{ $user->roles->pluck('name')->implode(',') }}</td>
                    <td>
                        @if($user->active)
                            <span class="label label-primary">{{ __('views.admin.users.index.active') }}</span>
                        @else
                            <span class="label label-danger">{{ __('views.admin.users.index.inactive') }}</span>
                        @endif
                    </td>
                    <td>
                        @if($user->confirmed)
                            <span class="label label-success">{{ __('views.admin.users.index.confirmed') }}</span>
                        @else
                            <span class="label label-warning">{{ __('views.admin.users.index.not_confirmed') }}</span>
                        @endif</td>
                    <td>{{ $user->created_at }}</td>
                    <td>{{ $user->updated_at }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.technician.show', [$user->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.show') }}">
                            <i class="fa fa-eye"></i>
                        </a>

                        @if($user->active)
                            <a id="deactivate" class="btn btn-xs btn-warning" href="{{ route('admin.technician.deactivate', ['id'=>$user->id]) }}" data-toggle="tooltip" data-placement="top" data-title="Deactivate Account">
                                <i class="fa fa-times-rectangle"></i>
                            </a>
                        @else
                            <a id="activate" class="btn btn-xs btn-success" href="{{ route('admin.technician.activate', ['id'=>$user->id]) }}" data-toggle="tooltip" data-placement="top" data-title="Activate Account">
                                <i class="fa fa-check-square"></i>
                            </a>
                        @endif

                        @if(auth()->user()->hasRole('administrator'))
                            <button class="btn btn-xs btn-danger user_destroy"
                                    data-url="{{ route('admin.users.destroy', [$user->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.delete') }}">
                                <i class="fa fa-trash"></i>
                            </button>
                        @endif
                    </td>
                </tr>
              @endif
            @endforeach
            </tbody>
        </table>
        <div class="pull-right">
            {{ $users->links() }}
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script>
        $('.user_destroy').click(function (e) {
            e.preventDefault()
            var delete_url = $(this).attr('data-url')
            console.log(delete_url)

            setTimeout(
                $.ajax({
                    url: delete_url,
                    method: 'DELETE',
                    data: {_token: "{{ csrf_token() }}"},
                    statusCode: {
                        200: function (data) {
                            swal('Success', 'User Account Deleted Successfully!', 'success')
                            window.location.reload()
                        },
                        500: function (err) {
                            swal('Failed', 'Error Processing Request!', 'error')
                            console.log(err)
                        }
                    }
                }), 2000
            )
        });

        $('#activate').click(function (e) {
            e.preventDefault()
            var activate_url = $(this).attr('href')

            setTimeout(
                $.ajax({
                    url: activate_url,
                    method: 'GET',
                    statusCode: {
                        200: function (data) {
                            swal('Success', 'Account Activated successfully!', 'success')
                            window.location.reload()
                        },
                        500: function (err) {
                            swal('Failed', 'Error Processing Request!', 'error')
                            console.log(err)
                        }
                    }
                }), 2000
            )
        })

        $('#deactivate').click(function (e) {
            e.preventDefault()
            var deactivate_url = $(this).attr('href')

            setTimeout(
                $.ajax({
                    url: deactivate_url,
                    method: 'GET',
                    statusCode: {
                        200: function (data) {
                            swal('Success', 'Account Deactivated successfully!', 'success')
                            window.location.reload();
                        },
                        500: function (err) {
                            swal('Failed', 'Error Processing Request!', 'error')
                            console.log(err)
                        }
                    }
                }), 2000
            )
        })
    </script>
    @endsection

resources/views/admin/technician/edit.blade.php
{{--


     Functionality Removed.
     Keeping it jst in case


--}}

{{--@extends('admin.layouts.admin')--}}

{{--@section('title',__('views.admin.users.edit.title',['name' => $user->first_name.' '.$user->last_name]) )--}}

{{--@section('content')--}}
    {{--<div class="row">--}}
        {{--<div class="col-md-12 col-sm-12 col-xs-12">--}}
            {{--{{ Form::open(['route'=>['admin.technician.update', $user->id],'method' => 'put','class'=>'form-horizontal form-label-left']) }}--}}
                {{--<div class="form-group">--}}
                    {{--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first_name" >--}}
                        {{--First Name--}}
                        {{--<span class="required">*</span>--}}
                    {{--</label>--}}
                    {{--<div class="col-md-6 col-sm-6 col-xs-12">--}}
                        {{--<input id="first_name" type="text" class="form-control col-md-7 col-xs-12 @if($errors->has('first_name')) parsley-error @endif"--}}
                               {{--name="first_name" value="{{ $user->first_name }}" required>--}}
                        {{--@if($errors->has('first_name'))--}}
                            {{--<ul class="parsley-errors-list filled">--}}
                                {{--@foreach($errors->get('first_name') as $error)--}}
                                        {{--<li class="parsley-required">{{ $error }}</li>--}}
                                {{--@endforeach--}}
                            {{--</ul>--}}
                        {{--@endif--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--<div class="form-group">--}}
                {{--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last_name" >--}}
                    {{--Last Name--}}
                    {{--<span class="required">*</span>--}}
                {{--</label>--}}
                {{--<div class="col-md-6 col-sm-6 col-xs-12">--}}
                    {{--<input id="last_name" type="text" class="form-control col-md-7 col-xs-12 @if($errors->has('last_name')) parsley-error @endif"--}}
                           {{--name="last_name" value="{{ $user->last_name }}" required>--}}
                    {{--@if($errors->has('last_name'))--}}
                        {{--<ul class="parsley-errors-list filled">--}}
                            {{--@foreach($errors->get('last_name') as $error)--}}
                                {{--<li class="parsley-required">{{ $error }}</li>--}}
                            {{--@endforeach--}}
                        {{--</ul>--}}
                    {{--@endif--}}
                {{--</div>--}}
            {{--</div>--}}

            {{--<div class="form-group">--}}
                {{--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">--}}
                    {{--{{ __('views.admin.users.edit.email') }}--}}
                    {{--<span class="required">*</span>--}}
                {{--</label>--}}
                {{--<div class="col-md-6 col-sm-6 col-xs-12">--}}
                    {{--<input id="email" type="email" class="form-control col-md-7 col-xs-12 @if($errors->has('email')) parsley-error @endif"--}}
                           {{--name="email" value="{{ $user->email }}" disabled>--}}
                    {{--@if($errors->has('email'))--}}
                        {{--<ul class="parsley-errors-list filled">--}}
                            {{--@foreach($errors->get('email') as $error)--}}
                                {{--<li class="parsley-required">{{ $error }}</li>--}}
                            {{--@endforeach--}}
                        {{--</ul>--}}
                    {{--@endif--}}
                {{--</div>--}}
            {{--</div>--}}

            {{--<div class="form-group">--}}
                {{--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="phone_number">--}}
                    {{--Phone Number--}}
                    {{--<span class="required">*</span>--}}
                {{--</label>--}}
                {{--<div class="col-md-6 col-sm-6 col-xs-12">--}}
                    {{--<input id="phone_number" type="text" class="form-control col-md-7 col-xs-12 @if($errors->has('phone_number')) parsley-error @endif"--}}
                           {{--name="phone_number" value="{{ $user->phone_number }}" required>--}}
                    {{--@if($errors->has('phone_number'))--}}
                        {{--<ul class="parsley-errors-list filled">--}}
                            {{--@foreach($errors->get('phone_number') as $error)--}}
                                {{--<li class="parsley-required">{{ $error }}</li>--}}
                            {{--@endforeach--}}
                        {{--</ul>--}}
                    {{--@endif--}}
                {{--</div>--}}
            {{--</div>--}}

                {{--@if(!$user->hasRole('administrator'))--}}
                    {{--<div class="form-group">--}}
                        {{--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="active" >--}}
                            {{--{{ __('views.admin.users.edit.active') }}--}}
                        {{--</label>--}}
                        {{--<div class="col-md-6 col-sm-6 col-xs-12">--}}
                            {{--<div class="checkbox">--}}
                                {{--<label>--}}
                                    {{--<input id="active" type="checkbox" class="@if($errors->has('active')) parsley-error @endif"--}}
                                           {{--name="active" @if($user->active) checked="checked" @endif value="1">--}}
                                    {{--@if($errors->has('active'))--}}
                                        {{--<ul class="parsley-errors-list filled">--}}
                                            {{--@foreach($errors->get('active') as $error)--}}
                                                {{--<li class="parsley-required">{{ $error }}</li>--}}
                                            {{--@endforeach--}}
                                        {{--</ul>--}}
                                    {{--@endif--}}
                                {{--</label>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</div>--}}

                    {{--<div class="form-group">--}}
                        {{--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="confirmed" >--}}
                            {{--Mark as Confirmed--}}
                        {{--</label>--}}
                        {{--<div class="col-md-6 col-sm-6 col-xs-12">--}}
                            {{--<div class="checkbox">--}}
                                {{--<label>--}}
                                    {{--<input id="confirmed" type="checkbox" class="@if($errors->has('confirmed')) parsley-error @endif"--}}
                                           {{--name="confirmed" @if($user->confirmed) checked="checked" @endif value="1">--}}
                                    {{--@if($errors->has('confirmed'))--}}
                                        {{--<ul class="parsley-errors-list filled">--}}
                                            {{--@foreach($errors->get('confirmed') as $error)--}}
                                                {{--<li class="parsley-required">{{ $error }}</li>--}}
                                            {{--@endforeach--}}
                                        {{--</ul>--}}
                                    {{--@endif--}}
                                {{--</label>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                {{--@endif--}}

            {{--<div class="form-group">--}}
                {{--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="phone_number">--}}
                    {{--ID Number / KRA PIN--}}
                    {{--<span class="required">*</span>--}}
                {{--</label>--}}
                {{--<div class="col-md-6 col-sm-6 col-xs-12">--}}
                    {{--<input id="id_no" type="text" class="form-control col-md-7 col-xs-12 @if($errors->has('id_no')) parsley-error @endif"--}}
                           {{--name="id_no" value="{{ $user->technician->id_card_no }}" required>--}}
                    {{--@if($errors->has('id_no'))--}}
                        {{--<ul class="parsley-errors-list filled">--}}
                            {{--@foreach($errors->get('id_no') as $error)--}}
                                {{--<li class="parsley-required">{{ $error }}</li>--}}
                            {{--@endforeach--}}
                        {{--</ul>--}}
                    {{--@endif--}}
                {{--</div>--}}
            {{--</div>--}}

            {{--<div class="form-group">--}}
                {{--<label class="control-label col-md-3 col-sm-3 col-xs-12" for="roles">--}}
                    {{--User Type--}}
                {{--</label>--}}
                {{--<div class="col-md-6 col-sm-6 col-xs-12">--}}
                    {{--<select id="roles" name="roles[]" class="select2" multiple="multiple" style="width: 100%" autocomplete="off" disabled="true">--}}
                        {{--@foreach($roles as $role)--}}
                            {{--<option @if($user->roles->find($role->id)) selected="selected" @endif value="{{ $role->id }}">{{ $role->name }}</option>--}}
                        {{--@endforeach--}}
                    {{--</select>--}}
                {{--</div>--}}
            {{--</div>--}}

            {{--<div class="form-group">--}}
                {{--<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">--}}
                    {{--<a class="btn btn-primary" href="{{ URL::previous() }}"> {{ __('views.admin.users.edit.cancel') }}</a>--}}
                    {{--<button type="submit" class="btn btn-success"> {{ __('views.admin.users.edit.save') }}</button>--}}
                {{--</div>--}}
            {{--</div>--}}
            {{--{{ Form::close() }}--}}
        {{--</div>--}}
    {{--</div>--}}
{{--@endsection--}}

{{--@section('styles')--}}
    {{--@parent--}}
    {{--{{ Html::style(asset('assets/admin/css/users/edit.css')) }}--}}
{{--@endsection--}}

{{--@section('scripts')--}}
    {{--@parent--}}
    {{--{{ Html::script(asset('assets/admin/js/users/edit.js')) }}--}}
{{--@endsection--}}

resources/views/admin/technician/map.blade.php
@extends('admin.layouts.admin')

@section('title', 'Technicians Map')

@section('content')
<div style="width: 100%; height: 500px;" id="technicians_map"></div>
@endsection
@section('scripts')
    @parent
    <script type="text/javascript">
        var map;
        var map_id = "technicians_map";
        var coordsurl = "{{ route('admin.technicians.coords') }}";
    </script>
    {{ Html::script(asset('assets/custom/js/plot.js')) }}
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDBYOlNSA5ofbvMRe6I-MHxdio2TgdXQU&callback=initMap"> </script>
@endsection

resources/views/admin/technician/report-print.blade.php
<?php
?>
@include('partials.mini.theme')

<div style="padding: 30px 15px;">
    <div class="btn-group">
        <button class="btn btn-sm btn-primary">PDF</button>
        <button class="btn btn-sm btn-primary">Excel</button>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>User Id</th>
            <th>Full Name</th>
            <th>Phone Number</th>
            <th>Email</th>
            <th>Gender</th>
            <th>Id No</th>
            <th>Active</th>
            <th>Joined</th>
        </tr>
        </thead>
        <tbody>
        @php($count = 1)
        @foreach($users as $user)
            <tr>
                <th scope="row">{{ $count++ }}</th>
                <td>{{ $user->id }}</td>
                <td>{{ $user->first_name." ".$user->last_name }}</td>
                <td>{{ $user->phone_number }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->technician->gender }}</td>
                <td>{{ $user->technician->id_no }}</td>
                <td>{{ $user->active ?'active': 'inactive' }}</td>
                <td>{{ $user->created_at }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>