routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');

Route::get('/about', 'HomeController@about')->name('about');

/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');

    Route::get('logout', 'LoginController@logout')->name('logout');

//    Route::post('register', 'RegisterController@register')->name('post.technicians');

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Admin routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>'admin'], function () {

    Route::group(['namespace'=>'Admin'], function(){

        // Dashboard
        Route::get('/', 'DashboardController@dashboard')->name('dashboard');

        // Charts
        Route::get('charts/', 'DashboardController@charts')->name('charts');

        // New Subscription plan
        Route::post('subscriptions/create/', 'DashboardController@createSubscription')->name('subscription.new');

        // Subscription plans
        Route::get('subscriptions/', 'DashboardController@subscriptions')->name('subscriptions');
        
        // Users
        Route::get('users', 'AdminController@index')->name('users');

    });

    /**
    * @Technicians
    */

    // All Technicians
    Route::get('technicians', 'TechnicianController@technicians')->name('technicians');

    // Technicians Map
    Route::get('technicians/map', 'TechnicianController@map')->name('technicians.map');

    // Get technician Certificates
    Route::get('technician/certificate/{filename}', 'TechnicianController@certificate')->name('technicians.certificate');

    // Get technician Good Conduct
    Route::get('technician/{user_id}/good-conduct/', 'TechnicianController@goodConduct')->name('technicians.good-conduct');

    // Get technician Good Conduct
    Route::get('technician/{user_id}/id-card/', 'TechnicianController@nationalIdCard')->name('technicians.id-card');

    // Technician Details
    Route::get('technician/{user}', 'TechnicianController@show')->name('technician.show');

    // Edit Technician Details
    Route::get('technician/{user}/edit', 'TechnicianController@edit')->name('technician.edit');

    // Delete User
    Route::delete('technician/{user}', 'TechnicianController@destroy')->name('users.destroy');

    // Get Technicians Coordinates
    Route::get('technicians/coordinates', 'TechnicianController@getCoordinates')->name('technicians.coords');

    // Activate Account
    Route::get('technician/activate/{id}', 'TechnicianController@activate')->name('technician.activate');

    // Deactivate Account
    Route::get('technician/deactivate/{id}', 'TechnicianController@deactivate')->name('technician.deactivate');

    /**
    * @Clients
    */

    // All Clients
    Route::get('clients/', 'ClientController@clients')->name('clients');

    // Activate Account
    Route::get('clients/activate/{id}', 'ClientController@activate')->name('clients.activate');

    // Deactivate Account
    Route::get('clients/deactivate/{id}', 'ClientController@deactivate')->name('clients.deactivate');

    /**
    * @Jobs
    */

    // All Jobs
    Route::get('/jobs', 'JobController@getAll')->name('jobs');
    
    // Complete Jobs
    Route::get('/jobs/complete', 'JobController@getAll')->name('jobs.complete');

    // Canceled Jobs
    Route::get('/jobs/canceled', 'JobController@cancelled')->name('jobs.canceled');

    // Unasigned Jobs
    Route::get('/jobs/unasigned', 'JobController@unasigned')->name('jobs.unasigned');

    // Assigned Jobs
    Route::get('/jobs/assigned', 'JobController@assigned')->name('jobs.assigned');


    /**
    * @Companies
    */

    // All Companies
    Route::get('companies', 'CompanyController@getAll')->name('companies');

    // New Company
    Route::get('companies/new', 'CompanyController@create')->name('companies.new');
    
    // Edit Company
    Route::post('companies/edit', 'CompanyController@edit')->name('companies.edit');

    // Preview Company
    Route::get('companies/show', 'CompanyController@preview')->name('companies.show');

    // Company map
    Route::get('companies/map', 'CompanyController@map')->name('companies.map');

    // Get Company Coordinates
    Route::get('companies/coordinates', 'CompanyController@getCoordinates')->name('companies.coords');


    /**
    * @Categories
    */

    // Get all catergories
    Route::get('categories', 'CategoryController@index')->name('categories');

    // Create new category
    Route::post('categories/new', 'CategoryController@create')->name('categories.create');

    // Delete category
    Route::post('category/delete', 'CategoryController@delete')->name('category.delete');

    // Get category view
    Route::get('categories/{slug}','CategoryController@services')->name('category.view');

    /**
    * @Services
    */

    // Create new category
    Route::post('service/new', 'ServiceController@create')->name('service.create');

    // Get service
    Route::get('service/get', 'ServiceController@get')->name('service.get');

    // Edit Service
    Route::post('service/edit', 'ServiceController@edit')->name('service.edit');

    // Delete Service
    Route::post('service/delete', 'ServiceController@delete')->name('service.delete');


    // Route::get('permissions', 'PermissionController@index')->name('permissions');
    // Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');


    // Reports
    Route::get('/reports', 'ReportsController@index')->name('reports');

    Route::get('/reports/filter/technicians', 'ReportsController@technicians')->name('filterby.tech');

    Route::get('reports/jobs/print/', 'ReportsController@printJobReports')->name('jobs.print');

    Route::get('reports/technicians/print/', 'ReportsController@printTechReports')->name('technicians.print');
});

// Technician Avatar
Route::get('technician/avatar/{filename}', [
  'uses'=> 'TechnicianController@avatar',
  'as'=>'avatar',
]);

// Fundi Profile / dashboard
Route::group(['prefix'=>'fundi'], function (){

    //
    Route::match(['get', 'post'], 'signup/', 'TechnicianController@register')->name('become.fundi');

    //
    Route::get('signup/process/{uid}', 'TechnicianController@selectState')->name('fundi.state');

    //
    Route::get('signup/process/{uid}/finish/', 'TechnicianController@create');

    //
    Route::get('signup/successful/{uid}', 'TechnicianController@signupSuccess')->name('fundi.success');

    //
    Route::get('send-app-link/{uuid}', 'TechnicianController@sendLink');

    //
    Route::group(['middleware'=>'auth:web'], function (){

        //
        Route::get('dashboard/', 'TechnicianController@fundiDashboard')->name('fundi.dashboard');

        //
        Route::get('dashboard/documents/', 'TechnicianController@fundiDocuments')->name('fundi.documents');

        //
        Route::get('dashboard/settings/', 'TechnicianController@settings')->name('fundi.settings');

        //
        Route::post('update/', 'TechnicianController@update')->name('fundi.update');

        //
        Route::post('upload/certificate', 'TechnicianController@uploadCertificate');

        //
        Route::post('upload/certificate-of-good-conduct', 'TechnicianController@uploadCertificateOfGoodConduct');

        //
        Route::post('upload/national-id-card', 'TechnicianController@uploadNationaIdCard');

        //
        Route::post('upload/profile-pic', 'TechnicianController@uploadProfilePic');

    });

});

// View category services
Route::get('category/service/{slug}','ServiceController@fetchServices')->name('category.services');


Route::get('/fundi/test/{uid}', 'TechnicianController@selectService');

app/Technician.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Models\Auth\User\User;
use App\Company;
use Carbon\Carbon;
use App\Models\Traits\Model as ModelTrait;

class Technician extends Model
{
    use ModelTrait;
    
    protected $hidden = [];

    protected $guarded = [];

    protected $table = 'technicians';

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class, 'company_employees', 'user_id', 'company_id');
    }

    public function isValidated()
    {
        if ($this->id_card_no == null || !$this->certificate_valid || !$this->$good_conduct_valid) {
            return false;
        }
        return true;
    }

    /**
     * Format createdate (m-d-Y: h:i:s)
     *
     * @param string
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        $date = new Carbon($value);
        return $date->format('m-d-Y: h:i:s');
    }

    /**
     * Format updatedate (m-d-Y: h:i:s)
     *
     * @param string
     * @return string
     */
    public function getUpdatedAtAttribute($value)
    {
        $date = new Carbon($value);

        return $date->format('m-d-Y: h:i:s');
    }
}

resources/views/admin/home.blade.php
@extends('admin.layouts.admin')

@section('title', 'PataFundi')

@section('content')

@endsection

resources/views/admin/permissions.blade.php
@extends('admin.layouts.admin')

@section('title', __('views.membership.title'))

@section('content')
    <div class="row">
        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>ID</th>
                <th>@sortablelink('email', __('views.membership.table_header_0'),['page' => $users->currentPage()])</th>
                <th>@sortablelink('name',  __('views.membership.table_header_1'),['page' => $users->currentPage()])</th>
                <th>{{ __('views.membership.table_header_2') }}</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->name }}</td>
                    <td>
                        @if($user->hasRoles(config('protection.except_roles')))
                            <div class="line_30 h5">
                                &nbsp;
                            </div>
                        @else
                            <a title="Repeat validation" class="btn btn-default pull-right" href="{{ route('admin.permissions.repeat',$user) }}">
                                <i class="fa fa-refresh" aria-hidden="true"></i>
                            </a>
                            @if($user->protectionValidation)
                                <table class="table table-striped table-bordered dt-responsive nowrap">
                                    <thead>
                                    <tr>
                                        <th>{{ __('views.membership.table_header_3') }}</th>
                                        <th>{{ __('views.membership.table_header_4') }}</th>
                                        <th>{{ __('views.membership.table_header_5') }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($user->protectionValidation->validation_result as $result)
                                        <tr>
                                            <td style="width: 30%">{{ $result['productModuleNumber'] }}</td>
                                            <td style="width: 10%">
                                                @if($result['valid'])
                                                    <span class="label label-primary">{{ __('views.membership.valid') }}</span>
                                                @else
                                                    <span class="label label-danger">{{ __('views.membership.not_valid') }}</span>
                                                @endif
                                            </td>
                                            <td>
                                                {{ isset($result['expires'])?$result['expires']:''  }}
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @else
                                <div class="line_30 h4">
                                    Not validated
                                </div>
                            @endif
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pull-right">
            Powered by <a href="http://netlicensing.io/?utm_source=Laravel_Boilerplate&utm_medium=github&utm_campaign=laravel_boilerplate&utm_content=poweredby" target="_blank"/>Labs64 NetLicensing</a>
        </div>
        <div class="pull-right">
            {{ $users->links() }}
        </div>
        <div>
            <h4>How To</h4>
            <ul>
              <li>Manage available membership plans - <a href="https://go.netlicensing.io/console/v2/content/vendor/licensetemplate.xhtml?filterkey=productModuleNumber&filtervalue={{ config('protection.membership.product_module_number') }}" target="_blank"/>NetLicensing Management Console » License Templates</a></li>
              <li>View and manage registered users - <a href="https://go.netlicensing.io/console/v2/content/vendor/licensee.xhtml?filterkey=productNumber&filtervalue={{ config('protection.product_number') }}" target="_blank"/>NetLicensing Management Console » Licensees</a></li>
            </ul>
        </div>
    </div>
@endsection

resources/views/admin/reports.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: reaper45
 * Date: 9/19/17
 * Time: 10:38 AM
 */
?>

@extends('admin.layouts.admin')

@section('title', 'Generate Reports')

@section('styles')
    @parent
    <style>
        .select2-container--default .select2-selection--single{
            border-radius: 0px !important;
        }
        .select2-container--default .select2-selection--single .select2-selection__arrow{
            top: 5px !important;
        }
        .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus{
            color: #fff;
            background-color: #172d44;
            border-radius: 0px !important;
        }
    </style>
    @endsection

@section('content')
    <div class="container">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><i class="fa fa-bar-chart"></i>&nbsp; Reports<small></small></h2>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div class="col-xs-3">
                        <!-- required for floating -->
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs tabs-left">
                            <li class="active"><a href="#jobs" data-toggle="tab">Jobs</a>
                            </li>
                            <li><a href="#technicians" data-toggle="tab">Technicians</a>
                            </li>
                            <li><a href="#companies" data-toggle="tab">Companies</a>
                            </li>
                            <li><a href="#clients" data-toggle="tab">Clients</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-xs-9">
                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div class="tab-pane active" id="jobs">
                                <p class="lead">Jobs Report</p>
                                <div class="row">
                                    <div class="col-md-4">
                                        <label for="">Filter by status</label>
                                        <select name="" id="filterJobsByStatus" class="form-control js-basic-single">
                                            <option value="all">All</option>
                                            <option value="pending">Pending</option>
                                            <option value="accepted">Accepted</option>
                                            <option value="cancelled">Canceled</option>
                                        </select>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="">Filter by category</label>
                                        <select name="job_category" id="filterJobsByCat" class="form-control js-basic-single">
                                            <option value="all" selected>All</option>
                                            @foreach($categories as $key => $category)
                                                <optgroup label="{{ $key }}">
                                                @foreach($category as $item)
                                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                                @endforeach
                                                </optgroup>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-md-4">
                                        <label class="control-label" for="from">From: </label>
                                        <input class="form-control from" type="text" id="from" name="job_from" data-language='en' >
                                        <label for="to">To: </label>
                                        <input class="form-control to" type="text" id="to" name="job_to" data-language='en' >
                                    </div>
                                </div>

                                <div class="text-right" style="padding-top: 20px;">
                                    <button id="exportjobreport" class="btn btn-success" type="button">Export</button>
                                </div>
                            </div>

                            <div class="tab-pane" id="technicians">
                                <p class="lead">Technicians Report</p>
                                <div class="row">
                                    <div class="col-md-4">
                                        <label for="">Filter by category</label>
                                        <select name="" id="filterTechByCat" class="form-control">
                                            <option value="all">All</option>
                                        </select>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="">Filter By Technician</label>
                                        <select name="" id="filterTechByIndividuals" class="form-control">
                                            <option value="all">All</option>
                                        </select>
                                    </div>
                                    <div class="col-md-4">
                                        <label class="control-label" for="from">From: </label>
                                        <input class="form-control from" type="text" id="from" name="tech_from" data-language='en' >
                                        <label for="to">To: </label>
                                        <input class="form-control to" type="text" id="to" name="tech_to" data-language='en' >
                                    </div>
                                </div>
                                <div class="text-right" style="padding-top: 20px;">
                                    <button id="exportechreport" class="btn btn-success" type="button">Export</button>
                                </div>
                            </div>

                            <div class="tab-pane" id="companies">
                                <p class="lead">Companies Report</p>
                            </div>
                            <div class="tab-pane" id="clients">
                                <p class="lead">Clients Report</p>
                            </div>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                </div>
            </div>
        </div>
    </div>
    @endsection

@section('scripts')
    @parent
    <script>
        $( function() {
            var dateFormat = "yy-mm-dd",
                from = $( ".from" ).datepicker({
                        defaultDate: "+1w",
                        changeMonth: true,
                        numberOfMonths: 3
                    }).on( "change", function() {
                        to.datepicker( "option", "minDate", getDate( this ) );
                    }),
                to = $( ".to" ).datepicker({
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 3
                }).on( "change", function() {
                    from.datepicker( "option", "maxDate", getDate( this ) );
                });

            function getDate( element ) {
                var date;
                try {
                    date = $.datepicker.parseDate( dateFormat, element.value );
                    console.log(date)
                } catch( error ) {
                    date = null;
                }

                return date;
            }
            } );
        $(document).ready(function() {
            $('.js-basic-single').select2();
        });

        $('#exportjobreport').click(function () {
            var status = $('#filterJobsByStatus').val()
            var category_id = $('#filterJobsByCat').val()
            var from = $( "input[name='job_from']" ).val()
            var to = $( "input[name='job_to']" ).val()

            var report_url = "{{ route('admin.jobs.print') }}"

            window.open(
                report_url+"?status="+status+"&category_id="+category_id+"&from="+from+"&to="+to,
                '_blank'
            );

        })

        $('#exportechreport').click(function () {
            var category = $('#filterTechByCat').val()
            var technician_id = $('#filterTechByIndividuals').val()
            var from = $( "input[name='tech_from']" ).val()
            var to = $( "input[name='tech_to']" ).val()

            var report_url = "{{ route('admin.technicians.print') }}"

            console.log('hit');
            window.open(
                report_url+"?category="+category+"&technician_id="+technician_id+"&from="+from+"&to="+to,
                '_blank'
            );

        })
    </script>
    @endsection

resources/views/admin/show.blade.php
@extends('admin.layouts.admin')

@section('title', __('views.admin.users.show.title', ['name' => $user->first_name.' '.$user->last_name ]))

@section('content')
    <div class="row">
        <table class="table table-striped table-hover">
            <tbody>
            <tr>
                <th>{{ __('views.admin.users.show.table_header_0') }}</th>
                <td><img src="{{ $user->avatar }}" class="user-profile-image"></td>
            </tr>

            <tr>
                <th>{{ __('views.admin.users.show.table_header_1') }}</th>
                <td>{{ $user->first_name.' '.$user->last_name }}</td>
            </tr>

            <tr>
                <th>{{ __('views.admin.users.show.table_header_2') }}</th>
                <td>
                    <a href="mailto:{{ $user->email }}">
                        {{ $user->email }}
                    </a>
                </td>
            </tr>
            <tr>
                <th>{{ __('views.admin.users.show.table_header_3') }}</th>
                <td>
                    {{ $user->roles->pluck('name')->implode(',') }}
                </td>
            </tr>
            <tr>
                <th>{{ __('views.admin.users.show.table_header_4') }}</th>
                <td>
                    @if($user->active)
                        <span class="label label-primary">{{ __('views.admin.users.show.active') }}</span>
                    @else
                        <span class="label label-danger">{{ __('views.admin.users.show.inactive') }}</span>
                    @endif
                </td>
            </tr>

            <tr>
                <th>{{ __('views.admin.users.show.table_header_5') }}</th>
                <td>
                    @if($user->confirmed)
                        <span class="label label-success">{{ __('views.admin.users.show.confirmed') }}</span>
                    @else
                        <span class="label label-warning">{{ __('views.admin.users.show.not_confirmed') }}</span>
                    @endif</td>
                </td>
            </tr>

            <tr>
                <th>{{ __('views.admin.users.show.table_header_6') }}</th>
                <td>{{ $user->created_at }} ({{ $user->created_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>{{ __('views.admin.users.show.table_header_7') }}</th>
                <td>{{ $user->updated_at }} ({{ $user->updated_at->diffForHumans() }})</td>
            </tr>
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/subscription.blade.php
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Large modal</button>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <h4>Text in a modal</h4>
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
        <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>

    </div>
  </div>
</div>