routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');

Route::get('/about', 'HomeController@about')->name('about');

/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');

    Route::get('logout', 'LoginController@logout')->name('logout');

//    Route::post('register', 'RegisterController@register')->name('post.technicians');

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Admin routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>'admin'], function () {

    Route::group(['namespace'=>'Admin'], function(){

        // Dashboard
        Route::get('/', 'DashboardController@dashboard')->name('dashboard');

        // Charts
        Route::get('charts/', 'DashboardController@charts')->name('charts');

        // New Subscription plan
        Route::post('subscriptions/create/', 'DashboardController@createSubscription')->name('subscription.new');

        // Subscription plans
        Route::get('subscriptions/', 'DashboardController@subscriptions')->name('subscriptions');
        
        // Users
        Route::get('users', 'AdminController@index')->name('users');

    });

    /**
    * @Technicians
    */

    // All Technicians
    Route::get('technicians', 'TechnicianController@technicians')->name('technicians');

    // Technicians Map
    Route::get('technicians/map', 'TechnicianController@map')->name('technicians.map');

    // Get technician Certificates
    Route::get('technician/certificate/{filename}', 'TechnicianController@certificate')->name('technicians.certificate');

    // Get technician Good Conduct
    Route::get('technician/{user_id}/good-conduct/', 'TechnicianController@goodConduct')->name('technicians.good-conduct');

    // Get technician Good Conduct
    Route::get('technician/{user_id}/id-card/', 'TechnicianController@nationalIdCard')->name('technicians.id-card');

    // Technician Details
    Route::get('technician/{user}', 'TechnicianController@show')->name('technician.show');

    // Edit Technician Details
    Route::get('technician/{user}/edit', 'TechnicianController@edit')->name('technician.edit');

    // Delete User
    Route::delete('technician/{user}', 'TechnicianController@destroy')->name('users.destroy');

    // Get Technicians Coordinates
    Route::get('technicians/coordinates', 'TechnicianController@getCoordinates')->name('technicians.coords');

    // Activate Account
    Route::get('technician/activate/{id}', 'TechnicianController@activate')->name('technician.activate');

    // Deactivate Account
    Route::get('technician/deactivate/{id}', 'TechnicianController@deactivate')->name('technician.deactivate');

    /**
    * @Clients
    */

    // All Clients
    Route::get('clients/', 'ClientController@clients')->name('clients');

    // Activate Account
    Route::get('clients/activate/{id}', 'ClientController@activate')->name('clients.activate');

    // Deactivate Account
    Route::get('clients/deactivate/{id}', 'ClientController@deactivate')->name('clients.deactivate');

    /**
    * @Jobs
    */

    // All Jobs
    Route::get('/jobs', 'JobController@getAll')->name('jobs');
    
    // Complete Jobs
    Route::get('/jobs/complete', 'JobController@getAll')->name('jobs.complete');

    // Canceled Jobs
    Route::get('/jobs/canceled', 'JobController@cancelled')->name('jobs.canceled');

    // Unasigned Jobs
    Route::get('/jobs/unasigned', 'JobController@unasigned')->name('jobs.unasigned');

    // Assigned Jobs
    Route::get('/jobs/assigned', 'JobController@assigned')->name('jobs.assigned');


    /**
    * @Companies
    */

    // All Companies
    Route::get('companies', 'CompanyController@getAll')->name('companies');

    // New Company
    Route::get('companies/new', 'CompanyController@create')->name('companies.new');
    
    // Edit Company
    Route::post('companies/edit', 'CompanyController@edit')->name('companies.edit');

    // Preview Company
    Route::get('companies/show', 'CompanyController@preview')->name('companies.show');

    // Company map
    Route::get('companies/map', 'CompanyController@map')->name('companies.map');

    // Get Company Coordinates
    Route::get('companies/coordinates', 'CompanyController@getCoordinates')->name('companies.coords');


    /**
    * @Categories
    */

    // Get all catergories
    Route::get('categories', 'CategoryController@index')->name('categories');

    // Create new category
    Route::post('categories/new', 'CategoryController@create')->name('categories.create');

    // Delete category
    Route::post('category/delete', 'CategoryController@delete')->name('category.delete');

    // Get category view
    Route::get('categories/{slug}','CategoryController@services')->name('category.view');

    /**
    * @Services
    */

    // Create new category
    Route::post('service/new', 'ServiceController@create')->name('service.create');

    // Get service
    Route::get('service/get', 'ServiceController@get')->name('service.get');

    // Edit Service
    Route::post('service/edit', 'ServiceController@edit')->name('service.edit');

    // Delete Service
    Route::post('service/delete', 'ServiceController@delete')->name('service.delete');


    // Route::get('permissions', 'PermissionController@index')->name('permissions');
    // Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');


    // Reports
    Route::get('/reports', 'ReportsController@index')->name('reports');

    Route::get('/reports/filter/technicians', 'ReportsController@technicians')->name('filterby.tech');

    Route::get('reports/jobs/print/', 'ReportsController@printJobReports')->name('jobs.print');

    Route::get('reports/technicians/print/', 'ReportsController@printTechReports')->name('technicians.print');
});

// Technician Avatar
Route::get('technician/avatar/{filename}', [
  'uses'=> 'TechnicianController@avatar',
  'as'=>'avatar',
]);

// Fundi Profile / dashboard
Route::group(['prefix'=>'fundi'], function (){

    //
    Route::match(['get', 'post'], 'signup/', 'TechnicianController@register')->name('become.fundi');

    //
    Route::get('signup/process/{uid}', 'TechnicianController@selectState')->name('fundi.state');

    //
    Route::get('signup/process/{uid}/finish/', 'TechnicianController@create');

    //
    Route::get('signup/successful/{uid}', 'TechnicianController@signupSuccess')->name('fundi.success');

    //
    Route::get('send-app-link/{uuid}', 'TechnicianController@sendLink');

    //
    Route::group(['middleware'=>'auth:web'], function (){

        //
        Route::get('dashboard/', 'TechnicianController@fundiDashboard')->name('fundi.dashboard');

        //
        Route::get('dashboard/documents/', 'TechnicianController@fundiDocuments')->name('fundi.documents');

        //
        Route::get('dashboard/settings/', 'TechnicianController@settings')->name('fundi.settings');

        //
        Route::post('update/', 'TechnicianController@update')->name('fundi.update');

        //
        Route::post('upload/certificate', 'TechnicianController@uploadCertificate');

        //
        Route::post('upload/certificate-of-good-conduct', 'TechnicianController@uploadCertificateOfGoodConduct');

        //
        Route::post('upload/national-id-card', 'TechnicianController@uploadNationaIdCard');

        //
        Route::post('upload/profile-pic', 'TechnicianController@uploadProfilePic');

    });

});

// View category services
Route::get('category/service/{slug}','ServiceController@fetchServices')->name('category.services');


Route::get('/fundi/test/{uid}', 'TechnicianController@selectService');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Job;
use App\Service;
use App\Company;
use App\Models\Traits\Model as ModelTrait;

class Category extends Model
{
    use ModelTrait;
    
    protected $fillable = ['name', 'slug', 'description'];

    public $hidden = array();

    public $timestamps = false;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function services()
    {
      return $this->hasMany(Service::class);
    }

    public function jobs()
    {
      return $this->hasMany(Job::class);
    }

    /**
    * @companies
    */
    public function companies()
    {
        return $this->belongsToMany(Company::class, 'company_categories', 'category_id', 'company_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    function __construct()
    {
    	$this->middleware('admin')->except('categoryServices');
    }

    /**
    * @getAll
    * @return view()
    */
    public function index(Request $request)
    {
        $categories = Category::all();

        foreach ($categories as $category){
            $services = $category->services->count();
            $category->services = $services;
        }

    	return view('admin.categories.all', ['categories'=>$categories]);
    }

    /**
    * @create
    * @return view()
    */
    public function create(Request $request)
    {
        $validate = Validator::make($request->all(),[
            'title'=>'required',
        ]);

        if($validate->fails()){
            return response([$validate->errors()], 500);
//            return redirect()->back()->withErrors(['errors'=>$validate->errors()]);
        }
        $title = $request->input('title');
        $desc = $request->input('desc');

        $category = new Category;
        $category->name = $title;
        $category->slug = str_slug($title);
        $category->description = $desc;

        if ($category->save()){
            return response(['success'=>'Category created successfully!'], 200);
        }

    	return response(['errors'=>'Error Processing request. Try Again!'], 500);
    }

    /**
     * Delete catetgory
     *
     * @param Request $request
     * @internal param $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Symfony\Component\HttpFoundation\Response
     */
    public function delete(Request $request)
    {
        if ($request->input('id')){
            $id = $request->input('id');

            $category = Category::find($id);
            if ($category){
                $category->delete();
                return response(['message'=>'Category deleted successfully!'], 200);
            }
        }
        return response(['message'=>'Error Processing request!'], 500);
    }

    /**
     * View Category Deteils
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Symfony\Component\HttpFoundation\Response
     * @internal param $
     */
    public function services(Request $request, $slug)
    {
        $category = Category::where('slug', $slug)->first();

        return view('admin.categories.view', ['category'=>$category]);
    }
}

resources/views/admin/categories/all.blade.php
@extends('admin.layouts.admin')

@section('title', 'Categories')

@section('styles')
    @parent()
    <style>
        .modal{
            z-index: 1050;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Categories </h2>

                        <button class="btn btn-sm btn-primary pull-right"  data-toggle="modal" data-target="#new_category">New Cartegory &nbsp;<i class="fa fa-plus"></i></button>
                        <div class="clearfix"></div>
                    </div>

                    <div class="x_content">
                        <div class="table-responsive">
                            <table class="table table-striped jambo_table bulk_action">
                                <thead>
                                <tr class="headings">
                                    {{--<th>--}}
                                        {{--<input type="checkbox" id="check-all" class="flat">--}}
                                    {{--</th>--}}
                                    <th class="column-title"># </th>
                                    <th class="column-title">Title </th>
                                    <th class="column-title">Services </th>
                                    <th class="column-title no-link last text-right"><span class="nobr">Action</span>
                                    </th>
                                </tr>
                                </thead>

                                <tbody>
                                @php($count = 1)
                                @foreach($categories as $category)
                                <tr class="even pointer">
                                    {{--<td class="a-center ">--}}
                                        {{--<input type="checkbox" class="flat" name="table_records">--}}
                                    {{--</td>--}}
                                    <td class="a-center">{{ $count }}</td>
                                    <td class=" "> {{ $category->name }} </td>
                                    <td class=" ">{{ $category->services }}</td>
                                    <td class="a-right a-right text-right">
                                        <input type="hidden" value="{{ $category->name }}">
                                        <a class="btn btn-sm btn-success btn-new-service" data-toggle="modal" data-target="#new_service"><i class="fa fa-plus"></i></a>
                                        <input type="hidden" value="{{ $category->id }}">
                                        <a class="btn btn-sm btn-danger btn-delete-category"><i class="fa fa-trash"></i></a>
                                        <a href="{{ route('admin.category.view', ['slug'=>$category->slug]) }}" class="btn btn-sm btn-primary btn-view-category"><i class="fa fa-eye"></i></a>
                                    </td>
                                </tr>
                                    @php($count++)
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('admin.categories.new')
    @endsection

@section('scripts')
    @parent()
    <script type="application/javascript">
        var new_category_url = "{{ route('admin.categories.create') }}";
        var new_service_url = "{{ route('admin.service.create') }}";

        $('.btn-new-service').click(function () {
            var name = $(this).prev().val()
            var id = $(this).next().val()

            console.log(name)

            $('#category_id').val(id);
            $('#category').val(name);
        })

        $('.btn-delete-category').click(function ()  {
            var token = "{{ csrf_token()  }}";

            var id = $(this).prev().val()
            var url = "{{ route('admin.category.delete') }}";

            setTimeout(
                $.ajax({
                    url: url,
                    method: 'POST',
                    data: {id: id, _token: token},
                    statusCode: {
                        500: function(err){
                            swal('Failled!', err.message, 'error')
                        }
                    },
                    success: function(data){
                        swal('Success!', data.message, 'success')
                        window.location.reload()
                    }
                }),
                2000
            )

        })

        $('#newCategory').submit(function (e) {
            e.preventDefault();
            var formdata = new FormData(this);

            $.ajax({
                url: new_category_url,
                method: 'POST',
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                statusCode: {
                    500: function(err){
                        console.log(err.errors)
                        swal('Failled!', 'Error Processing request. Try Again!', 'error')
                    },
                    200: function(data){
                        swal('Success!', data.message, 'success')
                        window.location.reload()
                    }
                }
            })
        })

        $('#newService').submit(function (e) {
            e.preventDefault();
            var formdata = new FormData(this);

            $.ajax({
                url: new_service_url,
                method: 'POST',
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                statusCode: {
                    500: function(err){
                        console.log(err.errors)
                        swal('Failled!', 'Error Processing request. Try Again!', 'error')
                    },
                    200: function(data){
                        swal('Success!', data.message, 'success')
                        window.location.reload()
                    }
                }
            })
        })
    </script>
    @endsection()

resources/views/admin/categories/view.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: reaper45
 * Date: 9/19/17
 * Time: 4:39 PM
 */
?>

@extends('admin.layouts.admin')

@section('title', 'Category')

@section('styles')
    @parent()

@endsection
@section('content')
    <div class="container">
        <div class="row">
            <button class='btn btn-sm btn-primary btn-new-service pull-right' data-toggle='modal' data-target='#new_service'><i class='fa fa-plus'></i>&nbsp;New Service</button>
            <h3 class="title"></h3>
            <table class="table-striped" id="serviceTab" class="display" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th></th>
                    <th>Service Name</th>
                    <th>Technicians</th>
                    <th>Jobs</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th></th>
                    <th>Service Name</th>
                    <th>Technicians</th>
                    <th>Jobs</th>
                    <th>Actions</th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>

{{--New service modal--}}
<div class="modal fade" id="new_service" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Create Service</h4>
            </div>
            {{ Form::open(['route'=>'admin.service.create', 'method'=> 'post', 'id'=>'new_service_form']) }}
            <input type="hidden" name="category_id" value="{{ $category->id }}">

            <div class="modal-body">
                <div class="form-group">

                    {{ Form::label('title', 'Category Title', ['class'=>'control-label']) }}
                    <input id="category"  class="form-control" type="text" value="{{ $category->name }}" disabled>
                </div>.

                <div class="form-group">
                    {{ Form::label('service', 'Service', ['class'=>'control-label']) }}
                    {{ Form::text('service', null, ['class'=>'form-control']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('desc', 'Description', ['class'=>'control-label']) }} <span class="info">&nbsp;(max: 250)</span>
                    <textarea name="desc" class="form-control" maxlength="250"></textarea>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" form="new_service_form" class="btn btn-primary">Save</button>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>

{{--Edit service modal--}}
<div class="modal fade" id="edit_service" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Edit Service</h4>
            </div>
            {{ Form::open(['route'=>'admin.service.edit', 'method'=> 'post', 'id'=>'edit_service_form']) }}

            <div class="modal-body">
                <input type="hidden" name="service_id" id="service_id" value="">
                <div class="form-group">
                    {{ Form::label('service_name', 'Service', ['class'=>'control-label']) }}
                    {{ Form::text('service_name', null, ['class'=>'form-control', 'id'=>'service_name', 'disabled'=>'true']) }}
                </div>
                <div class="form-group">
                    {{ Form::label('service_desc', 'Description', ['class'=>'control-label']) }} <span class="info">&nbsp;(max: 250)</span>
                    <textarea name="service_desc" id="service_desc" class="form-control" maxlength="250"></textarea>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" form="edit_service_form" class="btn btn-primary">Save</button>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>


@endsection
@section('scripts')
@parent
<!-- Datatables -->
<script>
    var get_service_url = "{{ route('admin.service.get') }}"
    var edit_service_url = "{{ route('admin.service.edit') }}";

    function format ( d ) {
        // `d` is the original data object for the row
        return '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">'+
            '<tr>'+
            '<td>Description:</td>'+
            '<td>'+d.description+'</td>'+
            '</tr>'+
            '</table>';
    }

    $(document).ready(function() {
        var table = $('#serviceTab').DataTable( {
            "ajax": "{{ route('category.services', ['slug'=>$category->slug]) }}",
            "columns": [
                {
                    "className":      'details-control',
                    "orderable":      false,
                    "data":           null,
                    "targets": 1,
                    "defaultContent": ""
                },
                { "data": "name" },
                { "data": "technicians" },
                { "data": "jobs" },
                { "data": "action" }
            ],
            "order": [[1, 'asc']]
        } );

        // Add event listener for opening and closing details
        $('#serviceTab tbody').on('click', 'td.details-control', function () {
            var tr = $(this).closest('tr');
            var row = table.row( tr );

            if ( row.child.isShown() ) {
                // This row is already open - close it
                row.child.hide();
                tr.removeClass('shown');
            }
            else {
                // Open this row
                row.child( format(row.data()) ).show();
                tr.addClass('shown');
            }
        });

        $('#serviceTab tbody').on( 'click', 'button.edit-service', function () {
            var id = $(this).next().val();
            var  modal = $('#edit_service');

            $.get(get_service_url, {id: id}, function(data, status){
                $('#service_id').val(data.service.id);
                $('#service_name').val(data.service.name);
                $('#service_desc').val(data.service.description);

                modal.modal()
            });

            $('#edit_service_form').submit(function (e) {
                e.preventDefault();
                var formdata = new FormData(this);

                setTimeout($.ajax({
                    url: edit_service_url,
                    method: 'POST',
                    data: formdata,
                    cache: false,
                    contentType: false,
                    processData: false,
                    statusCode: {
                        500: function (err) {
                            console.log(err)
                            swal('Failled!', 'Error Processing request. Try Again!', 'error')
                        },
                        200: function (data) {
                            swal('Success!', data.message, 'success')
                            window.location.reload()
                        }
                    }
                }), 3000)
            });
        });

        $('#serviceTab tbody').on( 'click', 'button.delete-service', function () {
            var id = $(this).prev('input').val();
            var del_url = "{{ route('admin.service.delete') }}";
            var token = "{{ csrf_token() }}";

            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then(function () {
                $.ajax({
                    url: del_url,
                    method: 'POST',
                    data: {id: id, _token: token},
                    statusCode: {
                        500: function () {
                            swal('Failed!','Error Processing your request.','error')
                        }
                    },
                    success: function () {
                        swal('Deleted!', 'Your file has been deleted.','success')
                        window.location.reload()
                    }
                })
            })
        } );
    } );

    var new_service_url = "{{ route('admin.service.create') }}";

    $('#new_service_form').submit(function (e) {
        e.preventDefault();
        var formdata = new FormData(this);

        setTimeout($.ajax({
            url: new_service_url,
            method: 'POST',
            data: formdata,
            cache: false,
            contentType: false,
            processData: false,
            statusCode: {
                500: function(err){
                    console.log(err)
                    swal('Failled!', 'Error Processing request. Try Again!', 'error')
                },
                200: function(data){
                    swal('Success!', data.message, 'success')
                    window.location.reload()
                }
            }
        }), 3000)
    });

</script>
    @endsection